{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-core",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.8-SNAPSHOT.jar",
          "url": "librarian-core-0.0.8-SNAPSHOT.jar",
          "size": 120914,
          "sha512": "3e2c7073730c61949199cb7dc4226e143e153f3f9d9fddbb22d79746bb5c9160e189e7578fa098ec99754d85a86f67717ddcec3af107aa824bc663f8a2b53ade",
          "sha256": "b27d2cedeb4f9a3fdb6e72309991ca6d061a2300599b83ebb925eba4e31abe81",
          "sha1": "79ad20f992f1286f3051cf8820e6e8b56584e344",
          "md5": "e5e3d295133c81c908e638b26159c827"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.8-SNAPSHOT.jar",
          "url": "librarian-core-0.0.8-SNAPSHOT.jar",
          "size": 120914,
          "sha512": "3e2c7073730c61949199cb7dc4226e143e153f3f9d9fddbb22d79746bb5c9160e189e7578fa098ec99754d85a86f67717ddcec3af107aa824bc663f8a2b53ade",
          "sha256": "b27d2cedeb4f9a3fdb6e72309991ca6d061a2300599b83ebb925eba4e31abe81",
          "sha1": "79ad20f992f1286f3051cf8820e6e8b56584e344",
          "md5": "e5e3d295133c81c908e638b26159c827"
        }
      ]
    }
  ]
}
