{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-core",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.8-SNAPSHOT.jar",
          "url": "librarian-core-0.0.8-SNAPSHOT.jar",
          "size": 120903,
          "sha512": "8004d76885d9703a70c5a00c2d271012a46e4173651d4759908c465307726e8d4a5154ac35372ae22806de94652d3415fb7b4b4f845efe75419c0761f77a7d51",
          "sha256": "c9b14b06859fd55e755bed79d7315e0de8270af4342f2e632f6e04fa3c8d9492",
          "sha1": "bc22587e2fb6e9300119ca58c3b44399435562a7",
          "md5": "7f8737e527e309db80143a39b67ed8ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.8-SNAPSHOT.jar",
          "url": "librarian-core-0.0.8-SNAPSHOT.jar",
          "size": 120903,
          "sha512": "8004d76885d9703a70c5a00c2d271012a46e4173651d4759908c465307726e8d4a5154ac35372ae22806de94652d3415fb7b4b4f845efe75419c0761f77a7d51",
          "sha256": "c9b14b06859fd55e755bed79d7315e0de8270af4342f2e632f6e04fa3c8d9492",
          "sha1": "bc22587e2fb6e9300119ca58c3b44399435562a7",
          "md5": "7f8737e527e309db80143a39b67ed8ef"
        }
      ]
    }
  ]
}
