{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-core",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.8-SNAPSHOT.jar",
          "url": "librarian-core-0.0.8-SNAPSHOT.jar",
          "size": 120914,
          "sha512": "14a64a0af051fd5de812811e82020b4076d446ea3eaced2eb1cdf500f2c5b8d04d0d66001843e5da7259efcd55229c0d451c4c5131a19f0a9fff85ffee466ddb",
          "sha256": "5825ea0a7db096b60ab6107c527960de9e493184f3c928506221997ad8f7d793",
          "sha1": "27da0470b0819327e491d372ca3e99aad2b7f31b",
          "md5": "7d037a2c67639a801c41c480b9492255"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.8-SNAPSHOT.jar",
          "url": "librarian-core-0.0.8-SNAPSHOT.jar",
          "size": 120914,
          "sha512": "14a64a0af051fd5de812811e82020b4076d446ea3eaced2eb1cdf500f2c5b8d04d0d66001843e5da7259efcd55229c0d451c4c5131a19f0a9fff85ffee466ddb",
          "sha256": "5825ea0a7db096b60ab6107c527960de9e493184f3c928506221997ad8f7d793",
          "sha1": "27da0470b0819327e491d372ca3e99aad2b7f31b",
          "md5": "7d037a2c67639a801c41c480b9492255"
        }
      ]
    }
  ]
}
