{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-core",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.8-SNAPSHOT.jar",
          "url": "librarian-core-0.0.8-SNAPSHOT.jar",
          "size": 120903,
          "sha512": "6efa4fcc5131c3ea899667015b0802a7c21cc75be24b54881b5cc0b66d60f2ed735b4345228f110cbcf23c3f70695a66e0dfacbb0d62ad888ad7e58849e2ad3e",
          "sha256": "52681ff139346c8d3707aff785aed07b5f0d4d2f2b673a8a0aaf1d0a071fb83f",
          "sha1": "c1da7daa45631384e54f830c5186b37ab7a8b628",
          "md5": "129fabd882982e3e1648de47348dff90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.8-SNAPSHOT.jar",
          "url": "librarian-core-0.0.8-SNAPSHOT.jar",
          "size": 120903,
          "sha512": "6efa4fcc5131c3ea899667015b0802a7c21cc75be24b54881b5cc0b66d60f2ed735b4345228f110cbcf23c3f70695a66e0dfacbb0d62ad888ad7e58849e2ad3e",
          "sha256": "52681ff139346c8d3707aff785aed07b5f0d4d2f2b673a8a0aaf1d0a071fb83f",
          "sha1": "c1da7daa45631384e54f830c5186b37ab7a8b628",
          "md5": "129fabd882982e3e1648de47348dff90"
        }
      ]
    }
  ]
}
