{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-core",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.7.jar",
          "url": "librarian-core-0.0.7.jar",
          "size": 120898,
          "sha512": "0d775b3e049bc316c36e182ff8a164ab21ed8f068d4d2c3bdfdd56d92190702c29394acbb5f4cea6e9042111a88c4480e9ee1e9f492e39f6a98e5e3f6d72ec5f",
          "sha256": "dc2c374d6aad7309025f8616886e21394faf680decd5cf26b503813f609d212e",
          "sha1": "fe487f96d89774e9b55b2d75d543ddb85cef7503",
          "md5": "985cb1b916dfa195e51040fb7ae9e36c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.7.jar",
          "url": "librarian-core-0.0.7.jar",
          "size": 120898,
          "sha512": "0d775b3e049bc316c36e182ff8a164ab21ed8f068d4d2c3bdfdd56d92190702c29394acbb5f4cea6e9042111a88c4480e9ee1e9f492e39f6a98e5e3f6d72ec5f",
          "sha256": "dc2c374d6aad7309025f8616886e21394faf680decd5cf26b503813f609d212e",
          "sha1": "fe487f96d89774e9b55b2d75d543ddb85cef7503",
          "md5": "985cb1b916dfa195e51040fb7ae9e36c"
        }
      ]
    }
  ]
}
