{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-gradle-plugin",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.15.0-Beta.2"
          }
        },
        {
          "group": "dev.adamko.dokkatoo",
          "module": "dokkatoo-plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-gradle-plugin-0.0.7-SNAPSHOT.jar",
          "url": "librarian-gradle-plugin-0.0.7-SNAPSHOT.jar",
          "size": 115041,
          "sha512": "c9dadb7bf89d06130f5e8896bcf52b79b5d6f09b2dced0ea55862eb746a8f3ed6c8809b9316642f0ec7e0782b78f24e33dbd4a57e2999d1ad9130448dcb7f511",
          "sha256": "30d48187c34508560883e9a5afd420bcfa567b7f08af92d805c02064001cd1b1",
          "sha1": "1a8ab49db8d0a3680b1c54148d17ea5657f33bb2",
          "md5": "d208a31bc2c23a0163313c50403dcd2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "net.mbonnin.vespene",
          "module": "vespene-lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "com.gradleup.maven-sympathy",
          "module": "maven-sympathy",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.15.0-Beta.2"
          }
        },
        {
          "group": "dev.adamko.dokkatoo",
          "module": "dokkatoo-plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-gradle-plugin-0.0.7-SNAPSHOT.jar",
          "url": "librarian-gradle-plugin-0.0.7-SNAPSHOT.jar",
          "size": 115041,
          "sha512": "c9dadb7bf89d06130f5e8896bcf52b79b5d6f09b2dced0ea55862eb746a8f3ed6c8809b9316642f0ec7e0782b78f24e33dbd4a57e2999d1ad9130448dcb7f511",
          "sha256": "30d48187c34508560883e9a5afd420bcfa567b7f08af92d805c02064001cd1b1",
          "sha1": "1a8ab49db8d0a3680b1c54148d17ea5657f33bb2",
          "md5": "d208a31bc2c23a0163313c50403dcd2d"
        }
      ]
    }
  ]
}
