name: 'Setup Librarian'
description: 'Installs "librarian" in PATH'

runs:
  using: 'composite'
  steps:
    - run: |
        ${{ github.action_path }}/../scripts/install.sh
        echo "$HOME/.librarian/bin" >> $GITHUB_PATH
      shell: bash
