name: 'Setup Librarian'
description: 'Installs "librarian" in PATH'

runs:
  using: 'composite'
  steps:
    - run: |
        ../scripts/install.sh
        echo "$HOME/.librarian/bin" >> $GITHUB_PATH
        librarian --version
      shell: bash
