{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-cli",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "size": 55920,
          "sha512": "8e05f62fa33ccbb4a267ea59cb77e580ba75dd15b4fcb615fbcc358189396d1f015933849f33daa0bbcab73f86d3cce63dc39fe236930bd5495f590e9a8099bd",
          "sha256": "5712132f7f38e083eff35dd49a0b38446703f3f0058a91a1a15a7de65ee851f9",
          "sha1": "2d5122e90ed675a6207ea2480e5f6a8c80eb17d4",
          "md5": "f5a5f981f406e60b7ad72fa8321b1864"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.kotlin-inquirer",
          "module": "kotlin-inquirer",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "size": 55920,
          "sha512": "8e05f62fa33ccbb4a267ea59cb77e580ba75dd15b4fcb615fbcc358189396d1f015933849f33daa0bbcab73f86d3cce63dc39fe236930bd5495f590e9a8099bd",
          "sha256": "5712132f7f38e083eff35dd49a0b38446703f3f0058a91a1a15a7de65ee851f9",
          "sha1": "2d5122e90ed675a6207ea2480e5f6a8c80eb17d4",
          "md5": "f5a5f981f406e60b7ad72fa8321b1864"
        }
      ]
    }
  ]
}
