{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-cli",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "size": 55920,
          "sha512": "3ec6aa950e3bb9da99e50d050566ff75b7cdb930ecb2b75849114ca97002aeb3e0deacf457710c6de802a72270808ad78d49c59dd18110c8156f16e43c5d7327",
          "sha256": "601210e72f614d39b1b3ba76e9f2078e2123bf6b59daf9f976313bc8f4d2c7f1",
          "sha1": "4e29f64d45ebb82c79359869fce599b27583ee4d",
          "md5": "71536beec3c483c407223fae0b26cde2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.kotlin-inquirer",
          "module": "kotlin-inquirer",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "size": 55920,
          "sha512": "3ec6aa950e3bb9da99e50d050566ff75b7cdb930ecb2b75849114ca97002aeb3e0deacf457710c6de802a72270808ad78d49c59dd18110c8156f16e43c5d7327",
          "sha256": "601210e72f614d39b1b3ba76e9f2078e2123bf6b59daf9f976313bc8f4d2c7f1",
          "sha1": "4e29f64d45ebb82c79359869fce599b27583ee4d",
          "md5": "71536beec3c483c407223fae0b26cde2"
        }
      ]
    }
  ]
}
