{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-cli",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "size": 55920,
          "sha512": "2ce489692a462e44ec782819e59539c5ecfdd509b1d040ac939075a0c212fab3ed93450c10e496ce210cd1b073e63e1bef89529707706a9cde54ba4c5f547c28",
          "sha256": "6580bc789bcca53c86727a43849db528adecf281c63debeb49282d67eea37127",
          "sha1": "842a8a0c9b92c89f3e74c87a92546edcaa448ade",
          "md5": "46e19df8ea76b2c55b5663a75ac42c5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.kotlin-inquirer",
          "module": "kotlin-inquirer",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "size": 55920,
          "sha512": "2ce489692a462e44ec782819e59539c5ecfdd509b1d040ac939075a0c212fab3ed93450c10e496ce210cd1b073e63e1bef89529707706a9cde54ba4c5f547c28",
          "sha256": "6580bc789bcca53c86727a43849db528adecf281c63debeb49282d67eea37127",
          "sha1": "842a8a0c9b92c89f3e74c87a92546edcaa448ade",
          "md5": "46e19df8ea76b2c55b5663a75ac42c5c"
        }
      ]
    }
  ]
}
