{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-cli",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "size": 55920,
          "sha512": "240aa072c0a0b1a99afb94c3e500b03c6728eded09092ab4927af6aa39e48eb44f0c91c83c822f922b9bf3e0946b2a20c27e4008145bceac83329e2184bfafe1",
          "sha256": "1a3f485c4ad6ffc77ddf2e72b3139a4bdb701a0b08c6d3ab508704db224027c3",
          "sha1": "e12cff8cb5346b39d7895ca26692a82427191455",
          "md5": "8a780854ac9a6f3a0cfe0d0d8bf4167c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.kotlin-inquirer",
          "module": "kotlin-inquirer",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.8-SNAPSHOT.jar",
          "size": 55920,
          "sha512": "240aa072c0a0b1a99afb94c3e500b03c6728eded09092ab4927af6aa39e48eb44f0c91c83c822f922b9bf3e0946b2a20c27e4008145bceac83329e2184bfafe1",
          "sha256": "1a3f485c4ad6ffc77ddf2e72b3139a4bdb701a0b08c6d3ab508704db224027c3",
          "sha1": "e12cff8cb5346b39d7895ca26692a82427191455",
          "md5": "8a780854ac9a6f3a0cfe0d0d8bf4167c"
        }
      ]
    }
  ]
}
