{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-gradle-plugin",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.16.3"
          }
        },
        {
          "group": "dev.adamko.dokkatoo",
          "module": "dokkatoo-plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-gradle-plugin-0.0.8-SNAPSHOT.jar",
          "url": "librarian-gradle-plugin-0.0.8-SNAPSHOT.jar",
          "size": 115127,
          "sha512": "1493b38d2c333c11737367f29edab1cfa75de8ecb6aa938a64450ca8c465fe7a13b76064dd1da3d9ba9cf92b98b6f6143298fd646c51c17ad7856267c47dae23",
          "sha256": "3405eb67ecb19b5d780018d42f22a9edd28cad0b4bbf8aa3b9fe04fac9293f57",
          "sha1": "5bf4633bc5edb3545e9b611654b0bce107d22e61",
          "md5": "159dba2f17a7edf1f70dcc7f5e1f5b9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "net.mbonnin.vespene",
          "module": "vespene-lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "com.gradleup.maven-sympathy",
          "module": "maven-sympathy",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.16.3"
          }
        },
        {
          "group": "dev.adamko.dokkatoo",
          "module": "dokkatoo-plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-gradle-plugin-0.0.8-SNAPSHOT.jar",
          "url": "librarian-gradle-plugin-0.0.8-SNAPSHOT.jar",
          "size": 115127,
          "sha512": "1493b38d2c333c11737367f29edab1cfa75de8ecb6aa938a64450ca8c465fe7a13b76064dd1da3d9ba9cf92b98b6f6143298fd646c51c17ad7856267c47dae23",
          "sha256": "3405eb67ecb19b5d780018d42f22a9edd28cad0b4bbf8aa3b9fe04fac9293f57",
          "sha1": "5bf4633bc5edb3545e9b611654b0bce107d22e61",
          "md5": "159dba2f17a7edf1f70dcc7f5e1f5b9a"
        }
      ]
    }
  ]
}
