{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-cli",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.7.jar",
          "url": "librarian-cli-0.0.7.jar",
          "size": 55902,
          "sha512": "635d6050cb776dbc9d2ccecf6a7eedfcd860795d1bbbd6307bc9e2dfbb2d7258726386ad609fe31f0ce88893bc75a2a3124283c73c292f5baa3a145072bd1fc2",
          "sha256": "39032f67dfc7282cc93d8ed0f8ec5f2ef71772ea42322ce4628651e5535d2ad5",
          "sha1": "0b7ec238cc907df7e352d820a44b54a35dd3afb8",
          "md5": "5b477092752efe8bf9cd1e82aef2566b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.kotlin-inquirer",
          "module": "kotlin-inquirer",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.7.jar",
          "url": "librarian-cli-0.0.7.jar",
          "size": 55902,
          "sha512": "635d6050cb776dbc9d2ccecf6a7eedfcd860795d1bbbd6307bc9e2dfbb2d7258726386ad609fe31f0ce88893bc75a2a3124283c73c292f5baa3a145072bd1fc2",
          "sha256": "39032f67dfc7282cc93d8ed0f8ec5f2ef71772ea42322ce4628651e5535d2ad5",
          "sha1": "0b7ec238cc907df7e352d820a44b54a35dd3afb8",
          "md5": "5b477092752efe8bf9cd1e82aef2566b"
        }
      ]
    }
  ]
}
