{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-cli",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "size": 56033,
          "sha512": "a3ecbd35fec4bf006eb9b5f25ea99ec5cd10086648b13eed957c9d3a854173f8e11a9ccb712a3f444857d7b305a38d424195000f1728c0d31b2b751d4a63d704",
          "sha256": "dd477ac3a918f3be0863d8e418719733131b2e374e7d4ac44e649068ebd7e98e",
          "sha1": "5b640f2d56e148d9d585cbffccc5e9f4e4a6b96f",
          "md5": "1d26b29c1faedd8d10a0108ce1ee88cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.kotlin-inquirer",
          "module": "kotlin-inquirer",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "size": 56033,
          "sha512": "a3ecbd35fec4bf006eb9b5f25ea99ec5cd10086648b13eed957c9d3a854173f8e11a9ccb712a3f444857d7b305a38d424195000f1728c0d31b2b751d4a63d704",
          "sha256": "dd477ac3a918f3be0863d8e418719733131b2e374e7d4ac44e649068ebd7e98e",
          "sha1": "5b640f2d56e148d9d585cbffccc5e9f4e4a6b96f",
          "md5": "1d26b29c1faedd8d10a0108ce1ee88cf"
        }
      ]
    }
  ]
}
