{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-cli",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "size": 56025,
          "sha512": "31079bc6fc4bcf0578f5a330b80aa211eee514636e8e894598c2fe2fef15cedc90a45d537af7bcadc2d66ff34ec9233e95abffe7d8ee7f11be880a5a9e610c48",
          "sha256": "5edd34b317aef2f4f0b21cd8d5bc16d1748d13b5c102bfa4f2501439a0e2a5d0",
          "sha1": "735413ea0b8cd5952cff048fa8193435af67d1d5",
          "md5": "3228cdd6ed3cb2876c66b2858fcdf1df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.kotlin-inquirer",
          "module": "kotlin-inquirer",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "size": 56025,
          "sha512": "31079bc6fc4bcf0578f5a330b80aa211eee514636e8e894598c2fe2fef15cedc90a45d537af7bcadc2d66ff34ec9233e95abffe7d8ee7f11be880a5a9e610c48",
          "sha256": "5edd34b317aef2f4f0b21cd8d5bc16d1748d13b5c102bfa4f2501439a0e2a5d0",
          "sha1": "735413ea0b8cd5952cff048fa8193435af67d1d5",
          "md5": "3228cdd6ed3cb2876c66b2858fcdf1df"
        }
      ]
    }
  ]
}
