{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-cli",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "size": 56025,
          "sha512": "b0d6a986379d211d3adaec85c82eda3cd38250f62b1bab23dd20e168a61aee40bb65d730832de4bda5371daf913b4008ff69b9ac93a2bd7be7b77de1e3d871ab",
          "sha256": "2bfb5738d3f394e81714c80eaf0b089e85d213b5787b1df6c10e1ea251373eef",
          "sha1": "c1131b121be529d98f78d80df032e33df180c74d",
          "md5": "4828ddef3d5d7107f6881476f3a10d95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.kotlin-inquirer",
          "module": "kotlin-inquirer",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "size": 56025,
          "sha512": "b0d6a986379d211d3adaec85c82eda3cd38250f62b1bab23dd20e168a61aee40bb65d730832de4bda5371daf913b4008ff69b9ac93a2bd7be7b77de1e3d871ab",
          "sha256": "2bfb5738d3f394e81714c80eaf0b089e85d213b5787b1df6c10e1ea251373eef",
          "sha1": "c1131b121be529d98f78d80df032e33df180c74d",
          "md5": "4828ddef3d5d7107f6881476f3a10d95"
        }
      ]
    }
  ]
}
