{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-cli",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "size": 55919,
          "sha512": "642d4c8b39f477829d82a8df43c70d08b4806c487263340fd03b674307c800ef3a1bafd178933d4d19aeb01944e0012a77914af65f095c66e127ab23ce0c8f47",
          "sha256": "8dfb71e3b77ee3d376d162e0a545097d6c9d6426368dd0c26dcf7f88a9d4653e",
          "sha1": "347fcbdf180ed929cbb165282ae3393fca30e1f1",
          "md5": "c2c106ca32c28f6121cc6a626aa8122a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.kotlin-inquirer",
          "module": "kotlin-inquirer",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "size": 55919,
          "sha512": "642d4c8b39f477829d82a8df43c70d08b4806c487263340fd03b674307c800ef3a1bafd178933d4d19aeb01944e0012a77914af65f095c66e127ab23ce0c8f47",
          "sha256": "8dfb71e3b77ee3d376d162e0a545097d6c9d6426368dd0c26dcf7f88a9d4653e",
          "sha1": "347fcbdf180ed929cbb165282ae3393fca30e1f1",
          "md5": "c2c106ca32c28f6121cc6a626aa8122a"
        }
      ]
    }
  ]
}
