{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-cli",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "size": 55919,
          "sha512": "305102b25cd9bdbd90e94316662cf9774f1fe3a10212d4c36ebca8fbd4e37041da13d48e1f174b33d90ed125d641431c7fb7170be7127703b41b50a8173f4d27",
          "sha256": "6d966dad886bb3a9abf29967a33245f1f08d353fe0f0990aaa05cf0036f8ccfc",
          "sha1": "9ab89603ace5793a343325bbdbab669b964fa84d",
          "md5": "f928495511b6b7e6efb61b6b4c33acb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.kotlin-inquirer",
          "module": "kotlin-inquirer",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "url": "librarian-cli-0.0.7-SNAPSHOT.jar",
          "size": 55919,
          "sha512": "305102b25cd9bdbd90e94316662cf9774f1fe3a10212d4c36ebca8fbd4e37041da13d48e1f174b33d90ed125d641431c7fb7170be7127703b41b50a8173f4d27",
          "sha256": "6d966dad886bb3a9abf29967a33245f1f08d353fe0f0990aaa05cf0036f8ccfc",
          "sha1": "9ab89603ace5793a343325bbdbab669b964fa84d",
          "md5": "f928495511b6b7e6efb61b6b4c33acb7"
        }
      ]
    }
  ]
}
