{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-gradle-plugin",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.15.0-Beta.2"
          }
        },
        {
          "group": "dev.adamko.dokkatoo",
          "module": "dokkatoo-plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-gradle-plugin-0.0.7-SNAPSHOT.jar",
          "url": "librarian-gradle-plugin-0.0.7-SNAPSHOT.jar",
          "size": 115038,
          "sha512": "db867a19a1f60748e05570431623689bfeabadcfb668ebb7f6f3b9185db36eaa7e10613ec5343c1eb7fe4d8a0adadab0b6e7b9cc6ada3803efc9712444d13f68",
          "sha256": "fd6d7f75abc12c53882c880566d06994de4e0c95dd69ab377990c358c1367443",
          "sha1": "f5ea16a6fc043abcd1cce4f7be8628edff8073fc",
          "md5": "1eb37d0bb1baf5c73157a54429f6096c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "net.mbonnin.vespene",
          "module": "vespene-lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "com.gradleup.maven-sympathy",
          "module": "maven-sympathy",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.15.0-Beta.2"
          }
        },
        {
          "group": "dev.adamko.dokkatoo",
          "module": "dokkatoo-plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-gradle-plugin-0.0.7-SNAPSHOT.jar",
          "url": "librarian-gradle-plugin-0.0.7-SNAPSHOT.jar",
          "size": 115038,
          "sha512": "db867a19a1f60748e05570431623689bfeabadcfb668ebb7f6f3b9185db36eaa7e10613ec5343c1eb7fe4d8a0adadab0b6e7b9cc6ada3803efc9712444d13f68",
          "sha256": "fd6d7f75abc12c53882c880566d06994de4e0c95dd69ab377990c358c1367443",
          "sha1": "f5ea16a6fc043abcd1cce4f7be8628edff8073fc",
          "md5": "1eb37d0bb1baf5c73157a54429f6096c"
        }
      ]
    }
  ]
}
