{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-gradle-plugin",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.15.0-Beta.2"
          }
        },
        {
          "group": "dev.adamko.dokkatoo",
          "module": "dokkatoo-plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-gradle-plugin-0.0.7-SNAPSHOT.jar",
          "url": "librarian-gradle-plugin-0.0.7-SNAPSHOT.jar",
          "size": 115031,
          "sha512": "037a3d01f1fa2498901dc2ef2b91e6fabc82f8042ef401c1030c14dc98229532c4ad34935a4f44b3fb6e0c439022f429ab28f2647046f91832ae3ded0a7ba74d",
          "sha256": "91012d2a15e550bd9d9d85dd64209d1187e20eda7897c0aec086b671b49e83f2",
          "sha1": "5799d31bc60318b42ea914edd4f385f82e3d492f",
          "md5": "4c49857c8ccefa6ab027f801773443f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "net.mbonnin.vespene",
          "module": "vespene-lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "com.gradleup.maven-sympathy",
          "module": "maven-sympathy",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.15.0-Beta.2"
          }
        },
        {
          "group": "dev.adamko.dokkatoo",
          "module": "dokkatoo-plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-gradle-plugin-0.0.7-SNAPSHOT.jar",
          "url": "librarian-gradle-plugin-0.0.7-SNAPSHOT.jar",
          "size": 115031,
          "sha512": "037a3d01f1fa2498901dc2ef2b91e6fabc82f8042ef401c1030c14dc98229532c4ad34935a4f44b3fb6e0c439022f429ab28f2647046f91832ae3ded0a7ba74d",
          "sha256": "91012d2a15e550bd9d9d85dd64209d1187e20eda7897c0aec086b671b49e83f2",
          "sha1": "5799d31bc60318b42ea914edd4f385f82e3d492f",
          "md5": "4c49857c8ccefa6ab027f801773443f2"
        }
      ]
    }
  ]
}
