{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "publishing",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "publishing-0.0.8-SNAPSHOT.jar",
          "url": "publishing-0.0.8-SNAPSHOT.jar",
          "size": 261,
          "sha512": "a0525915ae18ca6b7a3c7ef82a9b2cc34bff88d5ce6ec1851c11dfca442b8b97da0bf88424d04e54a552281444e342f35f9ff17eaa1a8791759478acc61a847c",
          "sha256": "b7eb1b40cd0acd5b79ab03eae50d58f461cf05042778e339270aa149e36c19e7",
          "sha1": "a98d3262b6483c61028eadd39ea1fd7c10f9547a",
          "md5": "972a179908c0ad0d1e087ad613d7f060"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "publishing-0.0.8-SNAPSHOT.jar",
          "url": "publishing-0.0.8-SNAPSHOT.jar",
          "size": 261,
          "sha512": "a0525915ae18ca6b7a3c7ef82a9b2cc34bff88d5ce6ec1851c11dfca442b8b97da0bf88424d04e54a552281444e342f35f9ff17eaa1a8791759478acc61a847c",
          "sha256": "b7eb1b40cd0acd5b79ab03eae50d58f461cf05042778e339270aa149e36c19e7",
          "sha1": "a98d3262b6483c61028eadd39ea1fd7c10f9547a",
          "md5": "972a179908c0ad0d1e087ad613d7f060"
        }
      ]
    }
  ]
}
