{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "publishing",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "publishing-0.0.8-SNAPSHOT.jar",
          "url": "publishing-0.0.8-SNAPSHOT.jar",
          "size": 261,
          "sha512": "50f9062f12bf7e260309dbcf5b38a62813343d153c581549d066335a57244e971e63a416719e90cfe84d3ff4ee7c0995e39ec5eb530debb369cb470da3672b4d",
          "sha256": "c8a9a2078a33bae77957d07ac0e083a5a8cb81965c959d12ea6f9626e67bee36",
          "sha1": "eee3b81b96593c61c648442f02cef19f8deb50ab",
          "md5": "5ae740f2be4ef93013e7b35e30fdb4b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.librarian",
          "module": "librarian-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "publishing-0.0.8-SNAPSHOT.jar",
          "url": "publishing-0.0.8-SNAPSHOT.jar",
          "size": 261,
          "sha512": "50f9062f12bf7e260309dbcf5b38a62813343d153c581549d066335a57244e971e63a416719e90cfe84d3ff4ee7c0995e39ec5eb530debb369cb470da3672b4d",
          "sha256": "c8a9a2078a33bae77957d07ac0e083a5a8cb81965c959d12ea6f9626e67bee36",
          "sha1": "eee3b81b96593c61c648442f02cef19f8deb50ab",
          "md5": "5ae740f2be4ef93013e7b35e30fdb4b1"
        }
      ]
    }
  ]
}
