{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-core",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.7-SNAPSHOT.jar",
          "url": "librarian-core-0.0.7-SNAPSHOT.jar",
          "size": 120916,
          "sha512": "6c3619423eefdded186f00259860ee7b1e694f19fdba0e76842e53e2299ca9eb1bc6c87b02cc96e8f964f988ea19a70e4a55f6a52e85029fa65e31fab19e519a",
          "sha256": "e5e5d0f3bd70f782368d895cc04913aaa55aebeb46a118fc1c56510428564b98",
          "sha1": "b398cd25167db2cc7eb601eac3ca33b2a697b222",
          "md5": "caab8bb11dcff81d41d1e3683ea7eb92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.7-SNAPSHOT.jar",
          "url": "librarian-core-0.0.7-SNAPSHOT.jar",
          "size": 120916,
          "sha512": "6c3619423eefdded186f00259860ee7b1e694f19fdba0e76842e53e2299ca9eb1bc6c87b02cc96e8f964f988ea19a70e4a55f6a52e85029fa65e31fab19e519a",
          "sha256": "e5e5d0f3bd70f782368d895cc04913aaa55aebeb46a118fc1c56510428564b98",
          "sha1": "b398cd25167db2cc7eb601eac3ca33b2a697b222",
          "md5": "caab8bb11dcff81d41d1e3683ea7eb92"
        }
      ]
    }
  ]
}
