{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-core",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.7-SNAPSHOT.jar",
          "url": "librarian-core-0.0.7-SNAPSHOT.jar",
          "size": 120947,
          "sha512": "5efd75d31891e40dc618b7425bc609277a0663769f443d97e8cd0dd087686fd339d3dfe692432d7d1d0278655a5a4ef9e78b81789dd3157e7ec75336c796089e",
          "sha256": "2220af375f59fd143d35c4f3e9659f6f0949e30ca3251a426cfab37895b436f3",
          "sha1": "9f764928fdbf220f0c1c31771618bb4db867a60a",
          "md5": "8d440d7fac94b5f6ef1556bbf4ee2d6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.7-SNAPSHOT.jar",
          "url": "librarian-core-0.0.7-SNAPSHOT.jar",
          "size": 120947,
          "sha512": "5efd75d31891e40dc618b7425bc609277a0663769f443d97e8cd0dd087686fd339d3dfe692432d7d1d0278655a5a4ef9e78b81789dd3157e7ec75336c796089e",
          "sha256": "2220af375f59fd143d35c4f3e9659f6f0949e30ca3251a426cfab37895b436f3",
          "sha1": "9f764928fdbf220f0c1c31771618bb4db867a60a",
          "md5": "8d440d7fac94b5f6ef1556bbf4ee2d6a"
        }
      ]
    }
  ]
}
