{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-core",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.7-SNAPSHOT.jar",
          "url": "librarian-core-0.0.7-SNAPSHOT.jar",
          "size": 120950,
          "sha512": "49248b7d716925a18a2bd29c9f99483141e75d4a7f441066d9120aa15d07bc5d0f9729229778541e7c9edc74b5ddf673d3072734df6fd82e1fee968773f4a5b4",
          "sha256": "980deaa244c8e888abcbdf11c0af108dee7d5136c3f3a953221a90d16b3cc56b",
          "sha1": "b79a8713982aef8ae46f9aee72752f32c547a099",
          "md5": "cf72d556fae6e13f54e462c97d91b971"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.7-SNAPSHOT.jar",
          "url": "librarian-core-0.0.7-SNAPSHOT.jar",
          "size": 120950,
          "sha512": "49248b7d716925a18a2bd29c9f99483141e75d4a7f441066d9120aa15d07bc5d0f9729229778541e7c9edc74b5ddf673d3072734df6fd82e1fee968773f4a5b4",
          "sha256": "980deaa244c8e888abcbdf11c0af108dee7d5136c3f3a953221a90d16b3cc56b",
          "sha1": "b79a8713982aef8ae46f9aee72752f32c547a099",
          "md5": "cf72d556fae6e13f54e462c97d91b971"
        }
      ]
    }
  ]
}
