{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.librarian",
    "module": "librarian-core",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.7-SNAPSHOT.jar",
          "url": "librarian-core-0.0.7-SNAPSHOT.jar",
          "size": 120950,
          "sha512": "afd1147416546a2a789cfb14416f2514233e4dfa539157d03a83ba24f2141dc7b8fde419d916500aa450220d1cebc25ff958d64edb4bdc61329f06d2a10ca442",
          "sha256": "396f0267b50941a3db255e67d451880ca79e0aef35569a921deb5c21bf94d2b5",
          "sha1": "49198a54af879614b219692500234b1d8fc5ab7e",
          "md5": "5028b208f121ccd2c34e54bdc4a83100"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "librarian-core-0.0.7-SNAPSHOT.jar",
          "url": "librarian-core-0.0.7-SNAPSHOT.jar",
          "size": 120950,
          "sha512": "afd1147416546a2a789cfb14416f2514233e4dfa539157d03a83ba24f2141dc7b8fde419d916500aa450220d1cebc25ff958d64edb4bdc61329f06d2a10ca442",
          "sha256": "396f0267b50941a3db255e67d451880ca79e0aef35569a921deb5c21bf94d2b5",
          "sha1": "49198a54af879614b219692500234b1d8fc5ab7e",
          "md5": "5028b208f121ccd2c34e54bdc4a83100"
        }
      ]
    }
  ]
}
