name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          # See https://github.com/cli/cli/issues/9558
          ref: ${{ github.ref }}
      - uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 #v4.2.2
      - run: |
          ./gradlew librarianPublishToMavenCentral
          gh release create $GITHUB_REF_NAME --title $GITHUB_REF_NAME --verify-tag --notes-from-tag
        env:
          LIBRARIAN_SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          LIBRARIAN_SONATYPE_USERNAME: ${{ secrets.OSSRH_USER }}
          LIBRARIAN_SIGNING_PRIVATE_KEY: ${{ secrets.GPG_KEY }}
          LIBRARIAN_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
          GH_TOKEN: ${{ github.token }}