name: release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - run: |
          ./gradlew librarianPublishToStaging
        env:
          LIBRARIAN_SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          LIBRARIAN_SONATYPE_USERNAME: ${{ secrets.OSSRH_USER }}
          LIBRARIAN_SIGNING_PRIVATE_KEY: ${{ secrets.GPG_KEY }}
          LIBRARIAN_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
